// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLiTNVx7epJe0yZW2HWKNiONc3E7F9-rA',
    appId: '1:751204311904:web:18a5ba19a0829c6c66b405',
    messagingSenderId: '751204311904',
    projectId: 'planpilot-app',
    authDomain: 'planpilot-app.firebaseapp.com',
    storageBucket: 'planpilot-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf4GXifvjEDZ-vL0hYjugp6qL3GAZ2shM',
    appId: '1:751204311904:android:1faf106125595fea66b405',
    messagingSenderId: '751204311904',
    projectId: 'planpilot-app',
    storageBucket: 'planpilot-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhuUKr-j_1BrKaN5NbRC-5BmA-5BqHvKQ',
    appId: '1:751204311904:ios:8b32dab7a44a520f66b405',
    messagingSenderId: '751204311904',
    projectId: 'planpilot-app',
    storageBucket: 'planpilot-app.appspot.com',
    iosBundleId: 'org.teKsafari.planpilot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhuUKr-j_1BrKaN5NbRC-5BmA-5BqHvKQ',
    appId: '1:751204311904:ios:b9712c0d0fe7546b66b405',
    messagingSenderId: '751204311904',
    projectId: 'planpilot-app',
    storageBucket: 'planpilot-app.appspot.com',
    iosBundleId: 'org.teKsafari.planpilot.RunnerTests',
  );
}
